use super::grant::{Grant, SignedGrant};
use crate::protocol::{decode, encode};
use ed25519_dalek::{Signer, SigningKey};
use rand::rngs::OsRng;
use snow::{
  params::DHChoice,
  resolvers::{CryptoResolver, DefaultResolver},
};
#[cfg(not(target_arch = "wasm32"))]
use std::path::Path;

#[cfg(not(target_arch = "wasm32"))]
mod native;
#[cfg(not(target_arch = "wasm32"))]
use native::load_or_create_secret;
use zeroize::Zeroizing;

pub(super) const NOISE_PROTOCOL: &str = "Noise_IK_25519_ChaChaPoly_BLAKE2s";

/// A local X25519 identity. Debug and serialization intentionally omit secrets.
#[derive(Clone)]
pub struct NoiseIdentity {
  secret: Zeroizing<[u8; 32]>,
  public: [u8; 32],
}

impl NoiseIdentity {
  pub fn generate() -> Result<Self, String> {
    let pair = snow::Builder::new(
      NOISE_PROTOCOL
        .parse()
        .map_err(|e| format!("Invalid Noise protocol: {e}"))?,
    )
    .generate_keypair()
    .map_err(|e| format!("Could not generate Noise identity: {e}"))?;
    let secret = Zeroizing::new(pair.private);
    Self::from_secret(
      secret
        .as_slice()
        .try_into()
        .map_err(|_| "Invalid generated private key")?,
    )
  }

  pub fn from_secret(secret: [u8; 32]) -> Result<Self, String> {
    let secret = Zeroizing::new(secret);
    let mut dh = DefaultResolver
      .resolve_dh(&DHChoice::Curve25519)
      .ok_or("X25519 is unavailable")?;
    dh.set(secret.as_ref());
    let public = dh.pubkey().try_into().map_err(|_| "Invalid X25519 public key")?;
    Ok(Self { secret, public })
  }

  /// Create a private file once, or load an existing regular, owner-only file.
  #[cfg(not(target_arch = "wasm32"))]
  pub fn load_or_create(path: &Path) -> Result<Self, String> {
    let secret = load_or_create_secret(path, "noise_x25519", || {
      let identity = Self::generate()?;
      Ok(*identity.secret)
    })?;
    Self::from_secret(*secret)
  }

  /// Read an existing private identity without creating or replacing any file.
  #[cfg(not(target_arch = "wasm32"))]
  pub fn load(path: &Path) -> Result<Self, String> {
    let secret = native::read_secret(path, "noise_x25519")?;
    Self::from_secret(*secret)
  }

  /// Import only canonical unpadded URL-safe base64 containing exactly 32 bytes.
  pub fn import_secret(value: &str) -> Result<Self, String> {
    if value.len() != 43 {
      return Err("Private key must be 32 bytes in unpadded URL-safe base64".into());
    }
    let secret = Zeroizing::new(decode(value, 32)?);
    if encode(&secret) != value {
      return Err("Private key must use canonical base64".into());
    }
    Self::from_secret(secret.as_slice().try_into().map_err(|_| "Invalid private key length")?)
  }

  /// Export explicitly for endpoint-owned private storage; never send to the Hub.
  pub fn export_secret(&self) -> String {
    encode(self.secret.as_ref())
  }

  pub fn public_key(&self) -> String {
    encode(&self.public)
  }

  pub fn private_key(&self) -> &[u8; 32] {
    &self.secret
  }
}

/// An owner-controlled signing identity, distinct from every transport key.
#[derive(Clone)]
pub struct OwnerIdentity(SigningKey);

impl OwnerIdentity {
  pub fn generate() -> Self {
    Self(SigningKey::generate(&mut OsRng))
  }

  #[cfg(not(target_arch = "wasm32"))]
  pub fn load_or_create(path: &Path) -> Result<Self, String> {
    let secret = load_or_create_secret(path, "owner_ed25519", || Ok(Self::generate().0.to_bytes()))?;
    Ok(Self(SigningKey::from_bytes(&secret)))
  }

  pub fn public_key(&self) -> String {
    encode(self.0.verifying_key().as_bytes())
  }

  /// Sign the exact typed grant; callers choose scope and expiry explicitly.
  pub fn sign_grant(&self, grant: Grant) -> Result<SignedGrant, String> {
    let signature = encode(&self.0.sign(&grant.signing_bytes()?).to_bytes());
    let signed = SignedGrant { grant, signature };
    signed.validate()?;
    Ok(signed)
  }
}

/// Public keys use canonical unpadded URL-safe base64, always exactly 32 bytes.
pub fn decode_public_key(value: &str) -> Result<[u8; 32], String> {
  if value.len() != 43 {
    return Err("Public key must be 32 bytes in unpadded URL-safe base64".into());
  }
  let bytes: [u8; 32] = decode(value, 32)?.try_into().map_err(|_| "Invalid public key length")?;
  if encode(&bytes) != value || bytes == [0; 32] {
    return Err("Invalid public key".into());
  }
  Ok(bytes)
}

/// Reject low-order X25519 points before using them as authorization identities.
/// A fixed, nonsecret clamped scalar is sufficient for this public point check:
/// low-order inputs yield an all-zero X25519 result. Session key agreement still
/// belongs entirely to Noise, with fresh secrets generated by its resolver.
pub(super) fn decode_noise_public_key(value: &str) -> Result<[u8; 32], String> {
  let bytes = decode_public_key(value)?;
  let mut dh = DefaultResolver
    .resolve_dh(&DHChoice::Curve25519)
    .ok_or("X25519 is unavailable")?;
  dh.set(&[0x42; 32]);
  let mut result = [0; 32];
  dh.dh(&bytes, &mut result).map_err(|_| "Invalid X25519 public key")?;
  if result == [0; 32] {
    return Err("Low-order X25519 public keys are not permitted".into());
  }
  Ok(bytes)
}

#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests {
  use super::*;
  use std::fs;

  #[test]
  fn read_only_noise_load_preserves_identity_and_never_creates_a_missing_key() {
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("noise.json");
    assert!(NoiseIdentity::load(&path).is_err());
    assert!(!path.exists());
    let identity = NoiseIdentity::load_or_create(&path).unwrap();
    let original = fs::read(&path).unwrap();
    assert_eq!(NoiseIdentity::load(&path).unwrap().public_key(), identity.public_key());
    assert_eq!(fs::read(&path).unwrap(), original);
  }

  #[test]
  fn exported_noise_secrets_restore_identity_and_reject_noncanonical_storage() {
    let identity = NoiseIdentity::generate().unwrap();
    let secret = Zeroizing::new(identity.export_secret());
    let restored = NoiseIdentity::import_secret(&secret).unwrap();
    assert_eq!(restored.public_key(), identity.public_key());
    assert_eq!(restored.private_key(), identity.private_key());
    let padded = Zeroizing::new(format!("{}=", secret.as_str()));
    assert!(NoiseIdentity::import_secret(&padded).is_err());
    assert!(NoiseIdentity::import_secret("not-a-private-key").is_err());
  }

  #[test]
  fn identities_round_trip_and_key_kinds_cannot_be_confused() {
    let directory = tempfile::tempdir().unwrap();
    let noise_path = directory.path().join("noise.json");
    let owner_path = directory.path().join("owner.json");
    let noise = NoiseIdentity::load_or_create(&noise_path).unwrap();
    let owner = OwnerIdentity::load_or_create(&owner_path).unwrap();
    assert_eq!(
      noise.public_key(),
      NoiseIdentity::load_or_create(&noise_path).unwrap().public_key()
    );
    assert_eq!(
      owner.public_key(),
      OwnerIdentity::load_or_create(&owner_path).unwrap().public_key()
    );
    assert!(OwnerIdentity::load_or_create(&noise_path).is_err());
    assert!(NoiseIdentity::load_or_create(&owner_path).is_err());
  }

  #[test]
  fn noise_identities_reject_low_order_public_points() {
    let mut point_one = [0; 32];
    point_one[0] = 1;
    assert!(decode_noise_public_key(&encode(&point_one)).is_err());
    assert!(decode_noise_public_key(&NoiseIdentity::generate().unwrap().public_key()).is_ok());
  }

  #[cfg(unix)]
  #[test]
  fn private_identities_reject_symlinks_hardlinks_and_insecure_permissions() {
    use std::os::unix::fs::{PermissionsExt, symlink};
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("identity");
    NoiseIdentity::load_or_create(&path).unwrap();
    assert_eq!(fs::metadata(&path).unwrap().permissions().mode() & 0o777, 0o600);
    let link = directory.path().join("link");
    symlink(&path, &link).unwrap();
    assert!(NoiseIdentity::load_or_create(&link).is_err());
    fs::remove_file(link).unwrap();
    fs::set_permissions(&path, fs::Permissions::from_mode(0o644)).unwrap();
    assert!(NoiseIdentity::load_or_create(&path).is_err());
    fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).unwrap();
    fs::hard_link(&path, directory.path().join("hardlink")).unwrap();
    assert!(NoiseIdentity::load_or_create(&path).is_err());
  }
}
